"""Describe your changes here

Revision ID: 979959d91cbc
Revises: 
Create Date: 2024-07-25 20:12:19.582696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979959d91cbc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendances', sa.Column('departure_type', sa.String(), nullable=True))
    op.add_column('attendances', sa.Column('departure_reason', sa.String(), nullable=True))
    op.add_column('attendances', sa.Column('supervisor', sa.String(), nullable=True))
    op.add_column('attendances', sa.Column('departure_time_actual', sa.Time(), nullable=True))
    op.add_column('attendances', sa.Column('return_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'return_time')
    op.drop_column('attendances', 'departure_time_actual')
    op.drop_column('attendances', 'supervisor')
    op.drop_column('attendances', 'departure_reason')
    op.drop_column('attendances', 'departure_type')
    # ### end Alembic commands ###
